version: '3.8'

services:
  web:
    build: 
      context: ../backend
      dockerfile: Dockerfile
    container_name: successfuel_backend_prod
    environment:
      - DATABASE_URL=\${DATABASE_URL}
      - JWT_SECRET_KEY=\${JWT_SECRET_KEY}
    ports:
      - "8000:8000"
    volumes:
      - ../backend:/app
    restart: unless-stopped